import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import './PublicBookingPage.css';
import InlineCalendar from './InlineCalendar';
import TimeSlotList from './TimeSlotList';
import { useToast } from '../context/ToastContext';
import API_BASE_URL from '../config/api';
import Loader from './Loader';

interface Calendar {
    id: number;
    title: string;
    duration: string;
    description: string;
    slug: string;
    therapist_name: string;
    profile_picture?: string;
    price?: number;
}

const PublicBookingPage: React.FC = () => {
    const { userId, slug } = useParams<{ userId: string; slug: string }>();
    const toast = useToast();

    const [calendar, setCalendar] = useState<Calendar | any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    // State for booking flow
    const [selectedDate, setSelectedDate] = useState<string>(new Date().toISOString().split('T')[0]);
    const [selectedSlot, setSelectedSlot] = useState<string | null>(null);
    const [step, setStep] = useState<'calendar' | 'details' | 'success'>('calendar');

    // Base Form data matching mandatory fields
    const [formData, setFormData] = useState({
        client_name: '',
        client_email: '',
        whatsapp_number: '',
        location: 'google_meet', // or 'in_person'
        payment_method: 'razorpay'
    });

    // Dynamic Form Answers capturing the varying questions generated by therapist
    const [formResponses, setFormResponses] = useState<Record<string, any>>({});

    const [termsAccepted, setTermsAccepted] = useState(false);

    useEffect(() => {
        const fetchCalendar = async () => {
            try {
                const response = await fetch(`${API_BASE_URL}/api/calendars/public/${userId}/${slug}`);
                if (response.ok) {
                    const data = await response.json();

                    // Pre-fill default dynamic answers if they exist
                    if (data.form_data && data.form_data.questions) {
                        const initialResponses: Record<string, any> = {};
                        data.form_data.questions.forEach((q: any) => {
                            if (q.type === 'checkbox') initialResponses[q.id] = [];
                            else initialResponses[q.id] = '';
                        });
                        setFormResponses(initialResponses);
                    }

                    setCalendar(data);
                } else {
                    setError('Calendar event not found.');
                }
            } catch (err) {
                setError('Failed to load calendar.');
            } finally {
                setLoading(false);
            }
        };

        if (userId && slug) {
            fetchCalendar();
        }
    }, [userId, slug]);

    const handleNext = () => {
        if (selectedDate && selectedSlot) {
            setStep('details');
            window.scrollTo(0, 0);
        }
    };

    const handleDynamicResponseChange = (questionId: string, value: any) => {
        setFormResponses(prev => ({ ...prev, [questionId]: value }));
    };

    const handleCheckboxChange = (questionId: string, option: string, checked: boolean) => {
        setFormResponses(prev => {
            const currentSelected = prev[questionId] || [];
            if (checked) {
                return { ...prev, [questionId]: [...currentSelected, option] };
            } else {
                return { ...prev, [questionId]: currentSelected.filter((opt: string) => opt !== option) };
            }
        });
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!calendar || !selectedSlot) return;
        if (!termsAccepted) {
            toast.warning('Please accept the Terms & Conditions.');
            return;
        }

        // Basic validation for dynamic required questions
        if (calendar.form_data && calendar.form_data.questions) {
            for (const q of calendar.form_data.questions) {
                if (q.required) {
                    const ans = formResponses[q.id];
                    if (ans === undefined || ans === null || ans === '' || (Array.isArray(ans) && ans.length === 0)) {
                        toast.warning(`Please fill out the required field: ${q.text}`);
                        return;
                    }
                }
            }
        }

        try {
            const payload = {
                calendar_id: calendar.id,
                start_time: selectedSlot,
                ...formData,
                client_phone: formData.whatsapp_number, // Map whatsapp to phone for now
                form_responses: formResponses // Send the JSON answer dump
            };

            const response = await fetch(`${API_BASE_URL}/api/bookings/public`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (response.ok) {
                setStep('success');
                window.scrollTo(0, 0);
            } else {
                const err = await response.json();
                toast.error(`Booking failed: ${err.error}`);
            }
        } catch (err) {
            toast.error('Network error. Please try again.');
        }
    };

    if (loading) return <Loader fullScreen />;
    if (error || !calendar) return <div className="error-screen">{error}</div>;

    if (step === 'success') {
        return (
            <div className="public-booking-container success-view">
                <div className="success-card">
                    <div style={{ fontSize: '48px', marginBottom: '20px' }}>🎉</div>
                    <h2>Booking Confirmed!</h2>
                    <p>You are scheduled with <strong>{calendar.therapist_name}</strong>.</p>
                    <p>A confirmation email has been sent to {formData.client_email}.</p>
                </div>
            </div>
        );
    }

    if (step === 'details') {
        // Parse date for display
        const dateObj = new Date(selectedSlot!);
        const dateStr = dateObj.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' }); // Tuesday, 10 February
        const timeStr = dateObj.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
        // Calculate end time roughly
        const endTime = new Date(dateObj.getTime() + (parseInt(calendar.duration) || 60) * 60000);
        const endTimeStr = endTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

        return (
            <div className="public-booking-container">
                <div className="booking-grid">
                    {/* Column 1: Service Details */}
                    <div className="col-service">
                        <div className="back-nav" style={{ marginBottom: '20px' }}>
                            <span style={{ cursor: 'pointer' }} onClick={() => setStep('calendar')}>&lt; Back</span>
                        </div>

                        <div className="logo-area" style={{ marginBottom: '20px' }}>
                            <img src="/Frame 2 1 (1).svg" alt="Logo" style={{ height: '30px' }} />
                        </div>

                        <h1 className="service-title">{calendar.title}</h1>
                        <div className="therapist-badge">
                            <span className="badge-label">Therapist:</span> {calendar.therapist_name}
                        </div>

                        <p className="service-desc">{calendar.description}</p>

                        <div className="service-meta">
                            <div className="meta-row">
                                <img src="/Clock.svg" alt="" width="16" />
                                <span>{calendar.duration}</span>
                            </div>
                            <div className="meta-row">
                                <img src="/Video.svg" alt="" width="16" />
                                <span>Google Meet</span>
                            </div>
                        </div>
                    </div>

                    <div className="col-details">
                        <form onSubmit={handleSubmit} className="details-form-card-inner">
                            <h2 className="details-heading">Enter Your Detail</h2>

                            <div className="selected-slot-summary">
                                <div className="slot-date-badge">
                                    <div className="month">{dateObj.toLocaleString('default', { month: 'short' }).toUpperCase()}</div>
                                    <div className="day">{dateObj.getDate()}</div>
                                </div>
                                <div className="slot-info-text">
                                    <div className="slot-date-text">{dateStr}</div>
                                    <div className="slot-time-text">{timeStr} - {endTimeStr} (GMT+05:30)</div>
                                </div>
                            </div>

                            <div className="form-group">
                                <label>Name <span className="required">*</span></label>
                                <input required type="text" className="form-input" value={formData.client_name} onChange={e => setFormData({ ...formData, client_name: e.target.value })} />
                            </div>

                            <div className="form-group">
                                <label>Email address <span className="required">*</span></label>
                                <input required type="email" className="form-input" value={formData.client_email} onChange={e => setFormData({ ...formData, client_email: e.target.value })} />
                            </div>

                            <div className="form-group">
                                <label>Whatsapp Number <span className="required">*</span></label>
                                <div className="phone-input-group">
                                    <span className="country-code">+91</span>
                                    <input required type="tel" className="form-input" value={formData.whatsapp_number} onChange={e => setFormData({ ...formData, whatsapp_number: e.target.value })} />
                                </div>
                            </div>

                            {/* Render Dynamic Questions */}
                            {calendar.form_data?.questions?.map((q: any) => (
                                <div key={q.id} className="form-group">
                                    <label>
                                        {q.text} {q.required && <span className="required">*</span>}
                                    </label>

                                    {q.type === 'text' && (
                                        <input
                                            type="text"
                                            className="form-input"
                                            required={q.required}
                                            value={formResponses[q.id] || ''}
                                            onChange={(e) => handleDynamicResponseChange(q.id, e.target.value)}
                                        />
                                    )}

                                    {q.type === 'long_text' && (
                                        <textarea
                                            className="form-textarea"
                                            rows={3}
                                            required={q.required}
                                            value={formResponses[q.id] || ''}
                                            onChange={(e) => handleDynamicResponseChange(q.id, e.target.value)}
                                        ></textarea>
                                    )}

                                    {q.type === 'phone' && (
                                        <div className="phone-input-group">
                                            <span className="country-code">+91</span>
                                            <input
                                                type="tel"
                                                className="form-input"
                                                required={q.required}
                                                value={formResponses[q.id] || ''}
                                                onChange={(e) => handleDynamicResponseChange(q.id, e.target.value)}
                                            />
                                        </div>
                                    )}

                                    {q.type === 'dropdown' && q.options && (
                                        <select
                                            className="form-input select-input"
                                            required={q.required}
                                            value={formResponses[q.id] || ''}
                                            onChange={(e) => handleDynamicResponseChange(q.id, e.target.value)}
                                        >
                                            <option value="">Select an option...</option>
                                            {q.options.map((opt: string, i: number) => (
                                                <option key={i} value={opt}>{opt}</option>
                                            ))}
                                        </select>
                                    )}

                                    {q.type === 'radio' && q.options && (
                                        <div className="radio-group" style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '8px' }}>
                                            {q.options.map((opt: string, i: number) => (
                                                <label key={i} className="radio-label" style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
                                                    <input
                                                        type="radio"
                                                        name={`radio-${q.id}`}
                                                        value={opt}
                                                        checked={formResponses[q.id] === opt}
                                                        onChange={(e) => handleDynamicResponseChange(q.id, e.target.value)}
                                                        required={q.required}
                                                    />
                                                    <span>{opt}</span>
                                                </label>
                                            ))}
                                        </div>
                                    )}

                                    {q.type === 'checkbox' && q.options && (
                                        <div className="checkbox-groups" style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '8px' }}>
                                            {q.options.map((opt: string, i: number) => (
                                                <label key={i} className="checkbox-label" style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
                                                    <input
                                                        type="checkbox"
                                                        checked={(formResponses[q.id] || []).includes(opt)}
                                                        onChange={(e) => handleCheckboxChange(q.id, opt, e.target.checked)}
                                                    />
                                                    <span>{opt}</span>
                                                </label>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            ))}

                            <div className="form-group checkbox-group" style={{ marginTop: '24px' }}>
                                <p style={{ margin: '10px 0', fontSize: '14px', color: '#333' }}>Please review the Terms & Conditions before completing your booking.</p>
                                <label className="checkbox-label">
                                    <input type="checkbox" checked={termsAccepted} onChange={e => setTermsAccepted(e.target.checked)} />
                                    <span>I confirm that I have read and agree to the Terms & Conditions</span>
                                </label>
                            </div>

                            {/* Location Section */}
                            <div className="form-section">
                                <label className="section-label">Select Location</label>
                                <div className="selection-cards">
                                    <div
                                        className={`selection-card ${formData.location === 'google_meet' ? 'selected' : ''}`}
                                        onClick={() => setFormData({ ...formData, location: 'google_meet' })}
                                    >
                                        <div className="card-radio">
                                            {formData.location === 'google_meet' && <div className="radio-inner" />}
                                        </div>
                                        <div className="card-content">
                                            <div className="card-title">
                                                <img src="/Google.svg" alt="" width="16" style={{ marginRight: '8px' }} />
                                                Google Meet
                                            </div>
                                            <div className="card-desc">Web conference using Google meet</div>
                                        </div>
                                    </div>

                                    <div
                                        className={`selection-card ${formData.location === 'in_person' ? 'selected' : ''}`}
                                        onClick={() => setFormData({ ...formData, location: 'in_person' })}
                                    >
                                        <div className="card-radio">
                                            {formData.location === 'in_person' && <div className="radio-inner" />}
                                        </div>
                                        <div className="card-content">
                                            <div className="card-title">In-person (Clinic)</div>
                                            <div className="card-desc">Lullanagar, Pune, Maharashtra 411040</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Price Section - only show if payment is enabled and prices are configured */}
                            {calendar.payment_enabled && calendar.prices && calendar.prices.length > 0 && (
                                <div className="form-section">
                                    <label className="section-label">Session Price</label>
                                    {calendar.prices.map((p: any, i: number) => (
                                        <div key={i} className="selection-card selected price-card">
                                            <div className="card-radio"><div className="radio-inner" /></div>
                                            <div className="card-content">
                                                <div className="card-title">{p.currency} {p.amount}</div>
                                                <div className="card-desc">{p.label || 'Session Charges'}</div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}

                            {/* Payment Method Section - only show if payment is enabled and gateway is configured */}
                            {calendar.payment_enabled && calendar.payment_gateway && (
                                <div className="form-section">
                                    <label className="section-label">Payment Method</label>
                                    <div className="selection-card selected">
                                        <div className="card-radio"><div className="radio-inner" /></div>
                                        <div className="card-content">
                                            <div className="card-title">
                                                {calendar.payment_gateway === 'razorpay' ? 'Razorpay'
                                                    : calendar.payment_gateway === 'cashfree' ? 'Cashfree'
                                                    : 'UPI/Cash'}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}

                            <div className="add-guests" style={{ margin: '20px 0', color: '#333', cursor: 'pointer', fontSize: '14px' }}>
                                + Add Guests
                            </div>

                            <div className="form-actions-footer">
                                <button type="submit" className="pay-confirm-btn">
                                    <img src="/Calendar.svg" alt="" style={{ filter: 'invert(1)', width: '16px', marginRight: '8px' }} />
                                    Pay and Confirm
                                </button>
                                <button type="button" onClick={() => setStep('calendar')} className="cancel-btn-outline">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="public-booking-container">
            <div className="booking-grid">
                {/* Column 1: Service Details */}
                <div className="col-service">
                    <div className="back-nav" style={{ marginBottom: '20px' }}>
                        <span style={{ cursor: 'pointer' }}>&lt; Back</span>
                    </div>

                    <div className="logo-area" style={{ marginBottom: '20px' }}>
                        <img src="/Frame 2 1 (1).svg" alt="Logo" style={{ height: '30px' }} />
                    </div>

                    <h1 className="service-title">{calendar.title}</h1>
                    <div className="therapist-badge">
                        <span className="badge-label">Therapist:</span> {calendar.therapist_name}
                    </div>

                    <p className="service-desc">{calendar.description}</p>

                    <div className="service-meta">
                        <div className="meta-row">
                            <img src="/Clock.svg" alt="" width="16" />
                            <span>{calendar.duration}</span>
                        </div>
                        <div className="meta-row">
                            <img src="/Video.svg" alt="" width="16" />
                            <span>Google Meet</span>
                        </div>
                    </div>
                </div>

                {/* Column 2: Date Selection */}
                <div className="col-calendar">
                    <div className="col-header">
                        <h2>Select a Date & Time</h2>
                        <div className="timezone-select">
                            <span>GMT+05:30</span>
                            <span className="down-arrow">▼</span>
                        </div>
                    </div>

                    <InlineCalendar
                        selectedDate={selectedDate}
                        onDateSelect={setSelectedDate}
                    />
                </div>

                {/* Column 3: Time Slots */}
                <div className="col-slots">
                    <TimeSlotList
                        calendarId={calendar.id}
                        selectedDate={selectedDate}
                        selectedSlot={selectedSlot}
                        onSlotSelect={(slot) => {
                            setSelectedSlot(slot);
                        }}
                    />
                    {selectedSlot && (
                        <div className="next-action-container">
                            <button onClick={handleNext} className="next-step-btn">
                                Next
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default PublicBookingPage;
